services:
  db:
    image: postgres:18
    container_name: agamewhereyou-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: agamewhereyou
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - agamewhereyou-db-data:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  agamewhereyou-db-data: