ktor {
  deployment {
    port = 8080
    port = ${?PORT}
    host = "127.0.0.1"
    host = ${?HOST}
  }
  database {
    url = "jdbc:postgresql://localhost:5432/agamewhereyou"
    url = ${?DATABASE_URL}
    user = ${?DB_USER}
    password = ${?DB_PASSWORD}
  }
  application {
    modules = [
      com.rekon.DIKt.configureDependencyInjection
      com.rekon.SerializationKt.configureSerialization
      com.rekon.ExposedKt.configureExposed
      com.rekon.StatusPagesKt.configureStatusPages
      com.rekon.RoutingKt.configureRouting
    ]
  }
}